DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(40) NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(800) NOT NULL,
  ROLE VARCHAR(20) NOT NULL,
);

INSERT INTO USER (NAME, COUNTRY, USERNAME, PASSWORD, ROLE) VALUES
  ('John Crom', 'Japan', 'john.crom', '$2a$10$BB1J66T/3kMcmidDah0R7OJtycBKlvJObNsW0DuSHYOoXmsVTt3bK', 'USER'),
  ('Carla Pike', 'United States of America', 'carla.pike', '$2a$10$BB1J66T/3kMcmidDah0R7OJtycBKlvJObNsW0DuSHYOoXmsVTt3bK', 'USER'),
  ('Thomas Fenmoy', 'Vietnam', 'thomas.fenmoy', '$2a$10$BB1J66T/3kMcmidDah0R7OJtycBKlvJObNsW0DuSHYOoXmsVTt3bK', 'USER');