CREATE TABLE IF NOT EXISTS user(
    user_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Language INT(2) NOT NULL,
    Gender INT(1) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    Picture VARCHAR(100),
    Hobby VARCHAR(100),
    Self VARCHAR(300),
    Age INT(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS gender(
    gender_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    gender_cap VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS lang(
    lang_id INT(10) PRIMARY KEY AUTO_INCREMENT,
    lang_cap VARCHAR(100)
);
